### ISSUE TITLE
Cambiar url de js

### ISSUE THREAD

**Issue by ajboni** [ggallotti/genexusweblibrary#1]
Hola, muy buena la libreria!
Es posible cambiar la url donde se busca el js? necesito levantarlo de un cdn pero aparentemente esta hardcodeado en algun lado que busque en la carpeta static. Gracias!

**Comment by ggallotti** [comment]
Gracias!
Lamentablemente esta "hardcodeado" en el Modulo. 
Y como es un Modulo externo, no podes cambiarlo.

Lo que podes hacer, es incluir la referencia al JS al CDN en el Head del WebPanel. 
Form.jssrc.add("http://cdn/...js")
Y lo que va a pasar es que le va a dar 404 el Request a tu server local. Pero la va a traer del CDN.

**Comment by ajboni** [comment]
> Lo que podes hacer, es incluir la referencia al JS al CDN en el Head del WebPanel.

Si, eso es lo que termine haciendo, molesta un poco el 404 en la consola, pero funciona. 
Gracias!
